### Registro de usuario 

POST http://127.0.0.1:4001/api/auth/new
Content-Type: application/json

{
    "name":"Pablo Gongora",
    "email":"pablo@google.com",
    "password":"123456"
}


### Login de usuario

POST http://127.0.0.1:4001/api/auth/
Content-Type: application/json

{
    "email":"pablo@google.com",
    "password":"123456"
}

### Refrescar token

GET http://127.0.0.1:4001/api/auth/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2OGNiMGI0MDVhMjM3ZmVmMGI5ODE3YWUiLCJuYW1lIjoiUGFibG8gR29uZ29yYSIsImlhdCI6MTc1ODEzNzE4MywiZXhwIjoxNzU4MTQ0MzgzfQ.dPVO8cmwmfHd5lv-71nT0srS3Oa_L_XQ0vL2UB2T5wY

